# Generated by Django 5.1.6 on 2025-02-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('is_corp', models.IntegerField(blank=True, null=True)),
                ('is_inactive', models.IntegerField(blank=True, null=True)),
                ('hs_object_id', models.IntegerField(blank=True, null=True)),
                ('hubspot_createdate', models.DateTimeField(blank=True, null=True)),
                ('hubspot_lastmodifieddate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('employee_division_id', models.IntegerField(blank=True, null=True)),
                ('employee_title_id', models.IntegerField(blank=True, null=True)),
                ('hs_object_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('hubspot_createdate', models.DateTimeField(blank=True, null=True)),
                ('hubspot_lastmodifieddate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HubSpotSyncHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100, unique=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(unique=True)),
                ('add_date', models.DateTimeField(blank=True, null=True)),
                ('add_user_id', models.IntegerField(blank=True, null=True)),
                ('cancel_date', models.DateField(blank=True, null=True)),
                ('contract_amount', models.FloatField(blank=True, null=True)),
                ('job_value', models.FloatField(blank=True, null=True)),
                ('hs_object_id', models.IntegerField(blank=True, null=True)),
                ('hubspot_createdate', models.DateTimeField(blank=True, null=True)),
                ('hubspot_lastmodifieddate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
