# Generated by Django 5.1.6 on 2025-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubspot_sync', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='division',
            old_name='hubspot_createdate',
            new_name='hs_createdate',
        ),
        migrations.RenameField(
            model_name='division',
            old_name='hubspot_lastmodifieddate',
            new_name='hs_lastmodifieddate',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='hubspot_createdate',
            new_name='add_date_time',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='hubspot_lastmodifieddate',
            new_name='hubspot_owner_assigneddate',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_value',
            new_name='accrued_commission_payout',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='hubspot_createdate',
            new_name='hs_createdate',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='hubspot_lastmodifieddate',
            new_name='hs_lastmodifieddate',
        ),
        migrations.RemoveField(
            model_name='job',
            name='id',
        ),
        migrations.AddField(
            model_name='division',
            name='hs_all_accessible_team_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_all_assigned_business_unit_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_all_owner_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_all_team_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_created_by_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_merged_object_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_object_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_object_source_detail_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_object_source_detail_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_object_source_detail_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_object_source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_object_source_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_object_source_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_pinned_engagement_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_read_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_shared_team_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_shared_user_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_unique_creation_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_updated_by_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_user_ids_of_all_notification_followers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_user_ids_of_all_notification_unfollowers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hs_was_imported',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hubspot_owner_assigneddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hubspot_owner_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='hubspot_team_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='is_omniscient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='is_utility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='is_vp_commission_ignored',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='paychex_company_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='region_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='division',
            name='rescission_period_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='add_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='advance_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='google_calender_channel_expiration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='google_calender_channel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='google_calender_last_sync',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='google_calender_resource_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='google_calender_sync_start',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hs_pinned_engagement_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hs_read_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hs_shared_team_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hs_shared_user_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hs_unique_creation_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hs_updated_by_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hs_user_ids_of_all_notification_followers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hs_user_ids_of_all_notification_unfollowers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hs_user_ids_of_all_owners',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hs_was_imported',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hubspot_owner_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hubspot_team_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='inactive_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='inactive_reason_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='inactive_reason_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='inactive_transfer_division_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_inactive',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lead_call_center',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lead_radius_distance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lead_radius_zip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lead_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='lead_views_allowed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='manager_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='project_commission_pct',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='timezone_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cancel_reason_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cancel_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='client_cid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='coc_sent_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='coc_sent_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cogs_report_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='commission_payout',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_cam_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_amount_difference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='deadline_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='deposit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='deposit_type_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='division_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='estimate_job_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='forecast_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hoa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hoa_approved',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_all_accessible_team_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_all_assigned_business_unit_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_all_owner_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_all_team_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_created_by_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_merged_object_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_object_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_object_source_detail_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_object_source_detail_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_object_source_detail_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_object_source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_object_source_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_object_source_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_pinned_engagement_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_read_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_shared_team_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_shared_user_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_unique_creation_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_updated_by_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_user_ids_of_all_notification_followers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_user_ids_of_all_notification_unfollowers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_user_ids_of_all_owners',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hs_was_imported',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hubspot_owner_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hubspot_team_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='install_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='install_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='install_time_format',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_cogs_report_month_updated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_company_cam',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_earned_not_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_financing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_five_star_review',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_in_progress',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_lead_pb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_payment_finalized',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_refund',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_reviewed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_sales_tax_exempt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_not_finalized_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pm_finished_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='pp_id_updated',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='prep_issue_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='prep_status_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='prep_status_is_reset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='prep_status_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='prep_status_set_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='price_level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='price_level_commission',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='price_level_commission_reduction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='price_level_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='production_month',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='production_user_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='project_coordinator_user_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='prospect_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ready_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ready_status',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reasons_other',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='refund_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='refund_user_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sales_tax_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='service_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sold_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='sold_user_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_month_old',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_request_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='subcontractor_confirmed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='subcontractor_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='subcontractor_status_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='time_format',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='user_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='group_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='hs_object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_corp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='is_inactive',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_division_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_title_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hs_object_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='add_user_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='hs_object_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HubSpotData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HubSpot Data',
                'verbose_name_plural': 'HubSpot Data',
                'unique_together': {('endpoint', 'record_id')},
            },
        ),
    ]
